version: "3"
services:
    php:
        container_name: php
        build:
            context: ./php
            dockerfile: Dockerfile
        ports:
          - "80:80"
          - "443:443"
        volumes:
            - "./api:/var/www/html"